# Generated by Django 4.2.6 on 2023-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('costumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='costumes', to='categories.categories'),
        ),
    ]
